name: Production Build

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  schedule:
    - cron: "30 10 1 1 *"
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Timezone
      uses: szenius/set-timezone@v1.0
      with:
        timezoneLinux: "Asia/Shanghai"
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v3.6.0
      with:
        node-version: 18.x
        cache: npm
        cache-dependency-path: yarn.lock
    - run: yarn
    - run: yarn build
    - run: vercel deploy ./jw1dev_dist --prod --yes --token=${{ secrets.VERCEL_TOKEN }} --regions=hkg1
    - run: node readme_gen.js
    - uses: EndBug/add-and-commit@v7
      with:
        add: README.md
        push: true
        message: 'Update README.md'
    - run: git status
