name: Production Build

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}

on:
  schedule:
    - cron: "30 10 1 1 *"
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: szenius/set-timezone@v1.0
      with:
        timezoneLinux: "Asia/Shanghai"
    - uses: actions/checkout@v2
    - run: npm i
    - run: npm run build
    - run: vercel deploy ./jw1dev_dist --prod --yes --token=${{ secrets.VERCEL_TOKEN }} --regions=hkg1
    - run: node readme_gen.js
    - uses: EndBug/add-and-commit@v7
      with:
        add: README.md
        push: true
        message: 'Update README.md'
    - run: git status
