name: Build page

on:
  schedule:
    - cron: "30 10 1 1 *"
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: szenius/set-timezone@v1.0
      with:
        timezoneLinux: "Asia/Shanghai"
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: node readme_gen.js
    - run: |
        git add README.md
        git commit -m "re-generate README.md" || echo "No changes to commit"
        git push origin main || echo "No changes to commit"
    - name: GitHub Pages
      uses: crazy-max/ghaction-github-pages@v2.5.0
      with: 
        jekyll: false
        build_dir: docs
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
